correct get ip

diff --git a/.github/workflows/get_IP.yml b/.github/workflows/get_IP.yml
--- a/.github/workflows/get_IP.yml
+++ b/.github/workflows/get_IP.yml
@@ -29,12 +29,29 @@ jobs:
           task_arn="${{ steps.get-task-arn.outputs.task_arn }}"
           aws ecs describe-tasks --cluster Develop --tasks $task_arn
 
-          public_ip=$(jq -r '.tasks[0].attachments[0].details[] | select(.name == "publicIPv4Address") | .value')
+          TASK_DESCRIPTION=$(aws ecs describe-tasks --cluster $CLUSTER_NAME --tasks $task_arn)
+          echo "Task Description: $TASK_DESCRIPTION"
 
-          echo "::set-output name=public_ip::$public_ip"
+          NETWORK_INTERFACE_ID=$(echo $TASK_DESCRIPTION | jq -r '.tasks[0].attachments[0].details[] | select(.name=="networkInterfaceId") | .value')
 
-        env:
-          AWS_REGION: us-east-1
+          # Debugging output
+          echo "Network Interface ID: $NETWORK_INTERFACE_ID"
+
+          if [ -z "$NETWORK_INTERFACE_ID" ] || [ "$NETWORK_INTERFACE_ID" == "null" ]; then
+            echo "Error: Failed to get network interface ID."
+            exit 1
+          fi
+          
+          PUBLIC_IP=$(aws ec2 describe-network-interfaces --network-interface-ids $NETWORK_INTERFACE_ID --query 'NetworkInterfaces[0].Association.PublicIp' --output text)
+
+          echo "Public IP Address: $PUBLIC_IP"
+
+          if [ -z "$PUBLIC_IP" ] || [ "$PUBLIC_IP" == "None" ]; then
+            echo "Error: Failed to get public IP address."
+            exit 1
+          fi
+
+          echo "Public IP Address: http://$PUBLIC_IP:8080/"
 
       - name: Display Task Info
         run: |
